INSERT INTO match (data) VALUES ('{
  "averageRating": 1,
  "startTime": 1,
  "matchDuration": 1,
  "picks": [
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    },
    {
      "playedId": 1,
      "heroName": 1,
      "netWorth": 1,
      "GPM": 1,
      "XPM": 1,
      "kills": 1,
      "assists": 1,
      "deaths": 1,
      "totalDamage": 1,
      "totalHeal": 1,
      "totalDamageTaken": 1,
      "wardsPlaced": 1,
      "teamGold": 1
    }
  ]
}');